version: '2'
services:
  nginx:
      build: nginx/.
      ports:
          - "8000:80"
      volumes:
          - ./:/var/www/html/handesk/
          - nginx:/etc/letsencrypt
      env_file: .env.nginx
      networks:
        - handesk-network

  php-fpm:
      build: .
      volumes:
        - ./:/var/www/html/handesk/
      env_file: .env
      environment:
         XDEBUG_HOST: ${XDEBUG_HOST}
      networks:
        - handesk-network

volumes:
  nginx:
    driver: local

networks:
  handesk-network:
